### ISSUE TITLE
node.iterationStatement is null to the format "for( ; ; )"

### ISSUE THREAD

**Issue by z2Z6** [Fraunhofer-AISEC/cpg#1015]
When the following `ForStatement` appears, the `NullPointerException` occurs
```java
public void test(){
    for (;;){
        System.out.println("1");
    }
}
```
exception
```java
java.util.concurrent.ExecutionException: java.lang.NullPointerException: node.iterationStatement must not be null
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at com.huawei.cra.core.core.CodePropertyGraph.buildCPG(CodePropertyGraph.java:69)
	... 28 more
Caused by: java.lang.NullPointerException: node.iterationStatement must not be null
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.handleForStatement(EvaluationOrderGraphPass.kt:883)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass._init_$lambda$20(EvaluationOrderGraphPass.kt:135)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.createEOG(EvaluationOrderGraphPass.kt:403)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.handleCompoundStatement(EvaluationOrderGraphPass.kt:510)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass._init_$lambda$14(EvaluationOrderGraphPass.kt:122)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.createEOG(EvaluationOrderGraphPass.kt:403)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.handleFunctionDeclaration(EvaluationOrderGraphPass.kt:347)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass._init_$lambda$4(EvaluationOrderGraphPass.kt:92)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.createEOG(EvaluationOrderGraphPass.kt:403)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.handleRecordDeclaration(EvaluationOrderGraphPass.kt:299)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass._init_$lambda$3(EvaluationOrderGraphPass.kt:89)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.createEOG(EvaluationOrderGraphPass.kt:403)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.handleTranslationUnitDeclaration(EvaluationOrderGraphPass.kt:270)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass._init_$lambda$1(EvaluationOrderGraphPass.kt:83)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.createEOG(EvaluationOrderGraphPass.kt:403)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.accept(EvaluationOrderGraphPass.kt:209)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.accept(EvaluationOrderGraphPass.kt:69)
	at de.fraunhofer.aisec.cpg.TranslationManager.analyze$lambda$2(TranslationManager.kt:102)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```
configuration: version 5.1.0
```java
     TranslationConfiguration.Builder()
                .sourceLocations(new File(fileName))
                .topLevel(null)
                .defaultPasses()
                .registerLanguage(JavaLanguageFrontend.class, JavaLanguageFrontend.JAVA_EXTENSIONS)
                .loadIncludes(false)
                .debugParser(false)
                .build();
```

**Comment by oxisto** [comment]
Thanks for catching this! This was a result of an improper conversion of the EOG pass to Kotlin. I am preparing a fix right now. Please not that we are currently in the process of preparing version `v6` with quite a lot of breaking changes, especially how language frontends work. Maybe I can release a back-ported version of it for the `v5` branch.
