### ISSUE TITLE
c++ chrono operator""ms error

### ISSUE THREAD

**Issue by peckto** [Fraunhofer-AISEC/cpg#1084]
# Stack trace

```
08:00:35,168 INFO  MeasurementHolder CXXLanguageFrontend: Parsing sourcefile main.cpp
08:00:35,567 INFO  CXXLanguageFrontend Parsed 281 bytes in main.cpp corresponding roughly to 5 LoC
08:00:35,580 INFO  MeasurementHolder CXXLanguageFrontend: Parsing sourcefile main.cpp done in 399 ms
08:00:35,580 INFO  MeasurementHolder CXXLanguageFrontend: Transforming main.cpp to CPG
08:00:35,621 INFO  MeasurementHolder TranslationManager: Translation into full graph done in 646 ms
java.util.concurrent.ExecutionException: java.lang.NumberFormatException: For input string: "250ms"
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at de.fraunhofer.aisec.cpg_vis_neo4j.Application.call(Application.kt:366)
	at de.fraunhofer.aisec.cpg_vis_neo4j.Application.call(Application.kt:66)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at de.fraunhofer.aisec.cpg_vis_neo4j.ApplicationKt.main(Application.kt:406)
Caused by: java.lang.NumberFormatException: For input string: "250ms"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.math.BigInteger.<init>(BigInteger.java:538)
	at de.fraunhofer.aisec.cpg.frontends.cpp.ExpressionHandler.handleIntegerLiteral(ExpressionHandler.kt:657)
	at de.fraunhofer.aisec.cpg.frontends.cpp.ExpressionHandler.handleLiteralExpression(ExpressionHandler.kt:490)
	at de.fraunhofer.aisec.cpg.frontends.cpp.ExpressionHandler.handleNode(ExpressionHandler.kt:58)
	at de.fraunhofer.aisec.cpg.frontends.cpp.ExpressionHandler.handleNode(ExpressionHandler.kt:53)
	at de.fraunhofer.aisec.cpg.frontends.cpp.CXXHandler.handle(CXXHandler.kt:56)
	at de.fraunhofer.aisec.cpg.frontends.cpp.InitializerHandler.handleEqualsInitializer(InitializerHandler.kt:68)
	at de.fraunhofer.aisec.cpg.frontends.cpp.InitializerHandler.handleNode(InitializerHandler.kt:43)
	at de.fraunhofer.aisec.cpg.frontends.cpp.InitializerHandler.handleNode(InitializerHandler.kt:38)
	at de.fraunhofer.aisec.cpg.frontends.cpp.CXXHandler.handle(CXXHandler.kt:56)
	at de.fraunhofer.aisec.cpg.frontends.cpp.DeclaratorHandler.handleDeclarator(DeclaratorHandler.kt:109)
	at de.fraunhofer.aisec.cpg.frontends.cpp.DeclaratorHandler.handleNode(DeclaratorHandler.kt:58)
	at de.fraunhofer.aisec.cpg.frontends.cpp.DeclaratorHandler.handleNode(DeclaratorHandler.kt:51)
	at de.fraunhofer.aisec.cpg.frontends.cpp.CXXHandler.handle(CXXHandler.kt:56)
	at de.fraunhofer.aisec.cpg.frontends.cpp.DeclarationHandler.handleSimpleDeclaration(DeclarationHandler.kt:501)
	at de.fraunhofer.aisec.cpg.frontends.cpp.DeclarationHandler.handleNode(DeclarationHandler.kt:63)
	at de.fraunhofer.aisec.cpg.frontends.cpp.DeclarationHandler.handleNode(DeclarationHandler.kt:58)
	at de.fraunhofer.aisec.cpg.frontends.cpp.CXXHandler.handle(CXXHandler.kt:56)
	at de.fraunhofer.aisec.cpg.frontends.cpp.StatementHandler.handleDeclarationStatement(StatementHandler.kt:292)
	at de.fraunhofer.aisec.cpg.frontends.cpp.StatementHandler.handleNode(StatementHandler.kt:52)
```

# Unexpected behavior

Since #1061 parsing a chrono `ms` values result in a crash.
The cpg seems to convert the ms literal to an integer, which fails.
Pre #1061, the example code could be parsed without error.
The value of the `ms` literal was `<error>`.

# Code of interest

```c++
#include <iostream>
#include <chrono>

int main()
{
    using namespace std::chrono_literals;
    auto d1 = 250ms;
    std::chrono::milliseconds d2 = 1s;
    std::cout << "250ms = " << d1.count() << " milliseconds\n"
              << "1s = " << d2.count() << " milliseconds\n";
    return 0;
}
```

# Extensions to the library, e.g. added or changed LanguageFrontends or Passes

None

# Changes to the configuration

None

**Comment by oxisto** [comment]
I am beginning to hate C++
