### ISSUE TITLE
When I analyze the project WebGoat-2023.8, it encountered IndexOutOfBoundsException

### ISSUE THREAD

**Issue by HaHarden** [Fraunhofer-AISEC/cpg#1491]
# Stack trace

```
Index 1 out of bounds for length 1
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at de.fraunhofer.aisec.cpg.frontends.Language.hasSignature(Language.kt:264)
	at de.fraunhofer.aisec.cpg.graph.declarations.FunctionDeclaration.hasSignature(FunctionDeclaration.kt:128)
	at de.fraunhofer.aisec.cpg.graph.declarations.FunctionDeclaration.hasSignature(FunctionDeclaration.kt:114)
	at de.fraunhofer.aisec.cpg.ScopeManager$resolveFunction$func$1.invoke(ScopeManager.kt:691)
	at de.fraunhofer.aisec.cpg.ScopeManager$resolveFunction$func$1.invoke(ScopeManager.kt:690)
	at de.fraunhofer.aisec.cpg.ScopeManager.resolve(ScopeManager.kt:1004)
	at de.fraunhofer.aisec.cpg.ScopeManager.resolveFunction(ScopeManager.kt:994)
	at de.fraunhofer.aisec.cpg.ScopeManager.resolveFunction$default(ScopeManager.kt:683)
	at de.fraunhofer.aisec.cpg.passes.SymbolResolver.resolveCalleeByName(SymbolResolver.kt:661)
	at de.fraunhofer.aisec.cpg.passes.SymbolResolver.resolveMemberCallee(SymbolResolver.kt:635)
	at de.fraunhofer.aisec.cpg.passes.SymbolResolver.resolveCallee(SymbolResolver.kt:563)
	at de.fraunhofer.aisec.cpg.passes.SymbolResolver.handleCallExpression(SymbolResolver.kt:501)
	at de.fraunhofer.aisec.cpg.passes.SymbolResolver.handle(SymbolResolver.kt:467)
	at de.fraunhofer.aisec.cpg.helpers.SubgraphWalker$ScopedWalker.registerHandler$lambda$0(SubgraphWalker.kt:415)
	at de.fraunhofer.aisec.cpg.helpers.SubgraphWalker$ScopedWalker.handleNode(SubgraphWalker.kt:458)
	at de.fraunhofer.aisec.cpg.helpers.SubgraphWalker$ScopedWalker.iterate$lambda$3$lambda$2(SubgraphWalker.kt:440)
	at de.fraunhofer.aisec.cpg.helpers.SubgraphWalker$IterativeGraphWalker.iterate$lambda$1(SubgraphWalker.kt:315)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at de.fraunhofer.aisec.cpg.helpers.SubgraphWalker$IterativeGraphWalker.iterate(SubgraphWalker.kt:315)
	at de.fraunhofer.aisec.cpg.helpers.SubgraphWalker$ScopedWalker.iterate(SubgraphWalker.kt:444)
	at de.fraunhofer.aisec.cpg.passes.SymbolResolver.accept(SymbolResolver.kt:106)
	at de.fraunhofer.aisec.cpg.passes.SymbolResolver.accept(SymbolResolver.kt:78)
	at de.fraunhofer.aisec.cpg.passes.PassKt.executePass(Pass.kt:357)
	at de.fraunhofer.aisec.cpg.TranslationManager.analyzeNonAsync(TranslationManager.kt:101)
	at de.fraunhofer.aisec.cpg.TranslationManager.analyze$lambda$0(TranslationManager.kt:69)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

# my test code

```kotlin
@Test
    fun myTest() {
        val file = File("D:\\WebGoat-2023.8")
        var topLevel = file.parentFile.toPath()
        val translationResult =
            myAnalyze(listOf(file), topLevel = topLevel) {
                it.registerLanguage<JavaLanguage>()
            }
        println(translationResult)
    }

fun myAnalyze(
        files: List<File>,
        topLevel: Path?,
        configModifier: Consumer<TranslationConfiguration.Builder>? = null
    ): TranslationResult {
        val builder =
            TranslationConfiguration.builder()
                .sourceLocations(files)
                .topLevel(topLevel?.toFile())
                .loadIncludes(false)
                .debugParser(true)
                .failOnError(false)
                .useParallelFrontends(true)
                .defaultPasses()
        configModifier?.accept(builder)
        val config = builder.build()
        val analyzer = TranslationManager.builder().config(config).build()
        val analyze = analyzer.analyze()
        return analyze.get()
    }

```

"WebGoat-2023.8" in the test code is a root directory of the project from the url: https://github.com/WebGoat/WebGoat/releases/tag/v2023.8
You can download the project and reproduce the error.

**Comment by HaHarden** [comment]
If I only register three Pass: TypeResolver,TypeHierarchyResolver and EvaluationOrderGraphPass, it's no error, but if I register another Pass: SymbolResolver, it encountered IndexOutOfBoundsException.

**Comment by KuechA** [comment]
Hi, could you check if #1493 solves this issue?

**Comment by HaHarden** [comment]
After resolving issue #1493, the IndexOutOfBoundsException continues to occur when testing the WebGoat-2023.8 Java project.

**Comment by KuechA** [comment]
I double checked with the PR and I do not see any problems with the changes.
