### ISSUE TITLE
NullPointerException when parsing cpp code

### ISSUE THREAD

**Issue by peckto** [Fraunhofer-AISEC/cpg#201]
I observed a NullPointerException in the CXXLanguageFrontend when parsing source code form 
`https://github.com/GENIVI/vsomeip.git`
```sh
$ ./build/install/cpg-vis-neo4j/bin/cpg-vis-neo4j ~/Downloads/vsomeip/
[...]
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
        at de.fraunhofer.aisec.cpg.ptn4j.Application.main(Application.kt:167)
Caused by: java.lang.NullPointerException
        at de.fraunhofer.aisec.cpg.frontends.cpp.CXXLanguageFrontend.parse(CXXLanguageFrontend.java:279)
        at de.fraunhofer.aisec.cpg.TranslationManager.runFrontends(TranslationManager.java:198)
        at de.fraunhofer.aisec.cpg.TranslationManager.lambda$analyze$0(TranslationManager.java:90)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

```

**Comment by Masrepus** [comment]
Seems like the CDT thinks that, for whatever reason, it saw comments at negative file offsets. These can't be parsed and result in  a `null` file location. Will fix this just now, but I guess we should upgrade to the newest CDT version @oxisto, a quick search turned out that there might be CDT 9.11.x instead of our 6.11 already...

**Comment by oxisto** [comment]
Don't be fooled by eclipse version logic. CDT 9.11 contains CDT Core 6.11 :)

The whole comment parsing is totally messed up at the moment, since comments from the source and header fill will be placed together in the same map and things are totally screwed up.

**Comment by Masrepus** [comment]
Oh wow, nice versioning...
