### ISSUE TITLE
NoClassDefFound Error

### ISSUE THREAD

**Issue by nikitamehrotra12** [Fraunhofer-AISEC/cpg#224]
Hi,

While using CPG as a library(.jar file) I am getting the following error:
```
C:\Users\nikita\eclipse-workspace\dataset\src\dataset\AddTwoNumbers.java
Exception in thread "main" java.lang.NoClassDefFoundError: com/github/javaparser/symbolsolver/model/resolution/TypeSolver
	at de.fraunhofer.aisec.cpg.TranslationConfiguration$Builder.defaultPasses(TranslationConfiguration.java:324)
	at dataset.CPGTEst.main(CPGTEst.java:17)
Caused by: java.lang.ClassNotFoundException: com.github.javaparser.symbolsolver.model.resolution.TypeSolver
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 2 more
```
I have used the same code provided with the readme with the modified file location:
```
public static void main(String[]args) throws InterruptedException, ExecutionException {
		Path path = Paths.get("C:\\Users\\nikita\\eclipse-workspace\\dataset\\src\\dataset\\Test.java");
		TranslationConfiguration config = TranslationConfiguration.builder().sourceLocations(path.toFile()).defaultPasses().debugParser(true).build();
		TranslationManager analyzer = TranslationManager.builder().config(config).build();
		TranslationResult result = analyzer.analyze().get();
		TranslationUnitDeclaration tu = result.getTranslationUnits().get(0);
	}
```
With this code, I am getting the above error. Could you please tell me what's wrong with the above usage?

Thanks

**Comment by oxisto** [comment]
Are you using some kind of dependency management system like maven or gradle? The readme contains a quick example how to use it as a library using Gradle's Kotlin-style build.gradle.kts

The problem is that the jar itself won't contain the needed dependencies, there is however a gradle task `./gradlew shadowJar` that should create a jar that contains all the necessary dependencies, so you could try to use this one. But I would really recommend getting familiar with a build system like gradle.

**Comment by nikitamehrotra12** [comment]
It worked thanks
