### ISSUE TITLE
Bug in EvaluationOrderGraphPass

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#271]
I will try to get a minimum viable crash sample. It seems to have been introduced somewhere after the 3.1.0 release. Originally, I blamed #263 but it seems to have been there before.

```
Caused by: java.lang.ClassCastException: class de.fraunhofer.aisec.cpg.passes.scopes.GlobalScope cannot be cast to class de.fraunhofer.aisec.cpg.passes.scopes.FunctionScope (de.fraunhofer.aisec.cpg.passes.scopes.GlobalScope and de.fraunhofer.aisec.cpg.passes.scopes.FunctionScope are in unnamed module of loader 'app')
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.handleFunctionDeclaration(EvaluationOrderGraphPass.java:271)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.createEOG(EvaluationOrderGraphPass.java:294)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.handleTranslationUnitDeclaration(EvaluationOrderGraphPass.java:223)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.createEOG(EvaluationOrderGraphPass.java:294)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.accept(EvaluationOrderGraphPass.java:165)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.accept(EvaluationOrderGraphPass.java:71)
	at de.fraunhofer.aisec.cpg.TranslationManager.lambda$analyze$0(TranslationManager.java:107)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1764)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by oxisto** [comment]
Looks like this bug has been here before, looks like cpg could not parse my project properly, however it should ideally not crash.
