### ISSUE TITLE
Accessing a non-existing key in recordMap can cause a NullPointerException in VariableUsageResolver

### ISSUE THREAD

**Issue by dentoir** [Fraunhofer-AISEC/cpg#328]
Hi,

When running CPG on a large batch of Java projects, I've seen the following exception being thrown several times:

```
Caused by: java.lang.NullPointerException
    at de.fraunhofer.aisec.cpg.passes.VariableUsageResolver.resolveFieldUsages(VariableUsageResolver.java:252)
    at de.fraunhofer.aisec.cpg.helpers.SubgraphWalker$ScopedWalker.lambda$registerHandler$0(SubgraphWalker.java:354)
    at de.fraunhofer.aisec.cpg.helpers.SubgraphWalker$ScopedWalker.handleNode(SubgraphWalker.java:391)
    at de.fraunhofer.aisec.cpg.helpers.SubgraphWalker$ScopedWalker.lambda$iterate$1(SubgraphWalker.java:364)
    at de.fraunhofer.aisec.cpg.helpers.SubgraphWalker$IterativeGraphWalker.lambda$iterate$1(SubgraphWalker.java:279)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1508)
    at de.fraunhofer.aisec.cpg.helpers.SubgraphWalker$IterativeGraphWalker.iterate(SubgraphWalker.java:279)
    at de.fraunhofer.aisec.cpg.helpers.SubgraphWalker$ScopedWalker.iterate(SubgraphWalker.java:366)
    at de.fraunhofer.aisec.cpg.passes.VariableUsageResolver.accept(VariableUsageResolver.java:112)
    at de.fraunhofer.aisec.cpg.passes.VariableUsageResolver.accept(VariableUsageResolver.java:71)
    at de.fraunhofer.aisec.cpg.TranslationManager.lambda$analyze$0(TranslationManager.java:107)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1771)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1763)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

The exception disappears when adding an explicit check for the presence of `curClass.getSuperClasses().get(0)` in `recordMap` at https://github.com/Fraunhofer-AISEC/cpg/blob/master/src/main/java/de/fraunhofer/aisec/cpg/passes/VariableUsageResolver.java#L251 like below:

```
          if (curClass != null
              && !curClass.getSuperClasses().isEmpty()
              && recordMap.containsKey(curClass.getSuperClasses().get(0))) {
```

However, I do not understand the source code well enough to understand whether this problem may not be caused by some issue elsewhere.

The exceptions occurred both with 3.3.1 and the current master version. I can't (yet) give a simple code snippet reproducing this issue, I'm afraid, because this particular dateset wasn't open-source.

Best regards,

Emile

**Comment by oxisto** [comment]
@dentoir Can you retry, if the https://github.com/Fraunhofer-AISEC/cpg/tree/fix-328 fixes this problem?

Before merging in this solution, I would try to understand it a little bit better, especially what we should do in this case. Would it be possible to try to set a breakpoint in https://github.com/Fraunhofer-AISEC/cpg/blob/6ceb8c741f4adc41d6a09353b6dbe4ab25212608/src/main/java/de/fraunhofer/aisec/cpg/passes/VariableUsageResolver.java#L259

I have also added a log command in this line, so you should at least get the super type and the class with the problem. Would be excellent if you could then share some characteristics about the class.

**Comment by dentoir** [comment]
Thanks for this patch! I will try to run it today and grab back any log/debug output.

**Comment by dentoir** [comment]
I've been running the branch and can report it works!

As far as debugging is concerned, the main thing I found is that it's looking for the class name in `recordMap` without full qualification - so without the package prefix. Both `superType.getTypeName()` and `superType.getName()` yield the simple class name without the package prefix. The class name *with* the fully qualified package name *is* present in recordMap, though.

The next observation is probably less useful. The scanned application was not designed by me. I can see that generics are involved. The superclass appears to be a custom collection, using generics. I'm obfuscating class names here, sorry about that. I'll be running the same application on a large batch of open-source data in the future. Perhaps I'll be able to trigger the issue there as well.

```
public abstract class Animals<T extends SomeAbstractClass> implements Behavior<T> {
...
}
```

```
public class Cat extends Animals<SomeClass> implements OtherBehavior {
...
}
```

Note: SomeClass *is* a valid extension of SomeAbstractClass here.

The error message would be 'Could not find referring super type Animals for Cat in the record map. This is a bit odd because they should have been parsed as well. Will set the super type to java.lang.Object'

**Comment by oxisto** [comment]
I finally managed to reproduce this. It looks like this was basically broken from the start and we just did not have a test case for accessing fields of a parent class using `super.`. I will look into what is going wrong here and try to fix the NPE as well as the behaviour.

**Comment by oxisto** [comment]
@dentoir I have updated the branch. Can you please check if it still works. It should now also deduce the type of the `super.` access correctly.

**Comment by dentoir** [comment]
Hi! Great to hear this has been fixed, I will be testing it on the master branch and report back when I still see a problem.
