### ISSUE TITLE
StackOverflowError in ControlFlowSensitiveDFGPass

### ISSUE THREAD

**Issue by peckto** [Fraunhofer-AISEC/cpg#346]
When loading the elua (https://github.com/elua/elua) source code into the cpg (v3.3.1), I observe an `StackOverflowError` inside the `ControlFlowSensitiveDFGPass`.
The error occurs when loading the `elua/src/lua/ldump.c` file.
The file has about 274 LOC. I do not load the includes.

```
$ JAVA_OPTS="-Xss1024m" ./build/install/cpg-vis-neo4j/bin/cpg-vis-neo4j  ~/Downloads/elua/src/lua/ldump.c               
13:44:19,592 INFO  TranslationManager Parsing /Downloads/elua/src/lua/ldump.c
13:44:20,797 INFO  CXXLanguageFrontend Parsed 74892 bytes corresponding roughly to 1497 LoC
13:44:20,798 INFO  Benchmark CXXLanguageFrontend Parsing sourcefile done in 763 ms
13:44:22,115 INFO  Benchmark CXXLanguageFrontend Transform to CPG done in 1316 ms
13:44:22,115 INFO  Benchmark TranslationManager Frontend done in 2543 ms
13:44:22,447 INFO  Benchmark TypeHierarchyResolver Executing Pass done in 331 ms
13:44:22,448 INFO  Benchmark JavaExternalTypeHierarchyResolver Executing Pass done in 0 ms
13:44:22,501 INFO  Benchmark ImportResolver Executing Pass done in 53 ms
13:44:22,869 WARN  Util file:///Downloads/elua/src/lua/ldump.c:257:42: Did not find a declaration for NULL
13:44:22,889 WARN  Util file:///Downloads/elua/src/lua/ldump.c:184:9: Did not find a declaration for NULL
13:44:22,891 WARN  Util file:///Downloads/elua/src/lua/ldump.c:184:28: Did not find a declaration for NULL
13:44:22,941 WARN  Util file:///Downloads/elua/src/lua/ldump.c:303:17: Did not find a declaration for NULL
13:44:23,019 INFO  Benchmark VariableUsageResolver Executing Pass done in 517 ms
13:44:23,392 INFO  Benchmark CallResolver Executing Pass done in 372 ms
13:44:23,457 INFO  EvaluationOrderGraphPass Parsing of type class de.fraunhofer.aisec.cpg.graph.declarations.IncludeDeclaration is not supported (yet)
13:44:23,458 INFO  EvaluationOrderGraphPass Parsing of type class de.fraunhofer.aisec.cpg.graph.declarations.IncludeDeclaration is not supported (yet)
13:44:23,458 INFO  EvaluationOrderGraphPass Parsing of type class de.fraunhofer.aisec.cpg.graph.declarations.IncludeDeclaration is not supported (yet)
13:44:23,458 INFO  EvaluationOrderGraphPass Parsing of type class de.fraunhofer.aisec.cpg.graph.declarations.IncludeDeclaration is not supported (yet)
13:44:23,595 INFO  Benchmark EvaluationOrderGraphPass Executing Pass done in 201 ms
13:44:23,679 INFO  Benchmark TypeResolver Executing Pass done in 83 ms
13:45:36,300 INFO  Benchmark TranslationManager Translation into full graph done in 76728 ms
java.util.concurrent.ExecutionException: java.lang.StackOverflowError
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
        at de.fraunhofer.aisec.cpg_vis_neo4j.Application.call(Application.kt:241)
        at de.fraunhofer.aisec.cpg_vis_neo4j.Application.call(Application.kt:45)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
        at picocli.CommandLine.execute(CommandLine.java:1904)
        at de.fraunhofer.aisec.cpg_vis_neo4j.ApplicationKt.main(Application.kt:266)
Caused by: java.lang.StackOverflowError
        at java.base/java.util.HashSet.<init>(HashSet.java:120)
        at de.fraunhofer.aisec.cpg.passes.ControlFlowSensitiveDFGPass$FunctionLevelFixpointIterator.registerOutgoingDFG(ControlFlowSensitiveDFGPass.java:161)
        at de.fraunhofer.aisec.cpg.passes.ControlFlowSensitiveDFGPass$FunctionLevelFixpointIterator.modifyDFGEdges(ControlFlowSensitiveDFGPass.java:199)
        at de.fraunhofer.aisec.cpg.passes.ControlFlowSensitiveDFGPass$FunctionLevelFixpointIterator.handleDeclaredReferenceExpression(ControlFlowSensitiveDFGPass.java:322)
        at de.fraunhofer.aisec.cpg.passes.ControlFlowSensitiveDFGPass$FunctionLevelFixpointIterator.propagateFromJoinPoints(ControlFlowSensitiveDFGPass.java:364)
        at de.fraunhofer.aisec.cpg.passes.ControlFlowSensitiveDFGPass$FunctionLevelFixpointIterator.propagateFromJoinPoints(ControlFlowSensitiveDFGPass.java:382)
        at de.fraunhofer.aisec.cpg.passes.ControlFlowSensitiveDFGPass$FunctionLevelFixpointIterator.propagateFromJoinPoints(ControlFlowSensitiveDFGPass.java:382)
        at de.fraunhofer.aisec.cpg.passes.ControlFlowSensitiveDFGPass$FunctionLevelFixpointIterator.propagateFromJoinPoints(ControlFlowSensitiveDFGPass.java:382)
        at de.fraunhofer.aisec.cpg.passes.ControlFlowSensitiveDFGPass$FunctionLevelFixpointIterator.propagateFromJoinPoints(ControlFlowSensitiveDFGPass.java:382)
[...]
```

Can you reproduce this error?

**Comment by oxisto** [comment]
Yep.. using jshell on the current master results in the same.

We have a recursion here: https://github.com/Fraunhofer-AISEC/cpg/blob/68bc752cf4034b4f26725fcfa35ef48c4ddca885/src/main/java/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.java#L382

We should / need to avoid recursions in the analysis code, we need to fix that.

**Comment by konradweiss** [comment]
I don't think that the recursion is the problem, most likely it is a case that we don't consider where we have to stop. Replacement by a loop would then not lead to a StackOverflowError, but in an infinit loop. I will look into it
