### ISSUE TITLE
Yet another StackOverflow error in the context-sensitive DFG pass

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#380]
# How to reproduce

By parsing the CPG using the CPG itself

```java
import de.fraunhofer.aisec.cpg.TranslationConfiguration;
import de.fraunhofer.aisec.cpg.TranslationManager;
import de.fraunhofer.aisec.cpg.graph.declarations.FunctionDeclaration;

var path = Paths.get("src/main/java");
var config = TranslationConfiguration.builder().sourceLocations(path.toFile()).defaultPasses().debugParser(true).build();
var analyzer = TranslationManager.builder().config(config).build();
var result = analyzer.analyze().get();
```

# Logs

```
|  Exception java.util.concurrent.ExecutionException: java.lang.StackOverflowError
|        at CompletableFuture.reportGet (CompletableFuture.java:395)
|        at CompletableFuture.get (CompletableFuture.java:2063)
|        at do_it$Aux (#7:1)
|        at (#7:1)
|  Caused by: java.lang.StackOverflowError
|        at Arrays.hashCode (Arrays.java:4498)
|        at Objects.hash (Objects.java:133)
|        at Node.hashCode (Node.java:401)
|        at ValueDeclaration.hashCode (ValueDeclaration.java:211)
|        at HashMap.hash (HashMap.java:340)
|        at HashMap.put (HashMap.java:612)
|        at HashSet.add (HashSet.java:221)
|        at AbstractCollection.addAll (AbstractCollection.java:336)
|        at HashSet.<init> (HashSet.java:121)
|        at ControlFlowSensitiveDFGPass$FunctionLevelFixpointIterator.registerOutgoingDFG (ControlFlowSensitiveDFGPass.java:160)
|        at ControlFlowSensitiveDFGPass$FunctionLevelFixpointIterator.modifyDFGEdges (ControlFlowSensitiveDFGPass.java:198)
|        at ControlFlowSensitiveDFGPass$FunctionLevelFixpointIterator.handleDeclaredReferenceExpression (ControlFlowSensitiveDFGPass.java:328)
|        at ControlFlowSensitiveDFGPass$FunctionLevelFixpointIterator.iterateTillFixpoint (ControlFlowSensitiveDFGPass.java:256)
|        at ControlFlowSensitiveDFGPass$FunctionLevelFixpointIterator.handleDeclaredReferenceExpression (ControlFlowSensitiveDFGPass.java:311)
|        at ControlFlowSensitiveDFGPass$FunctionLevelFixpointIterator.iterateTillFixpoint (ControlFlowSensitiveDFGPass.java:256)
|        at ControlFlowSensitiveDFGPass$FunctionLevelFixpointIterator.iterateTillFixpoint (ControlFlowSensitiveDFGPass.java:274)
|        at ControlFlowSensitiveDFGPass$FunctionLevelFixpointIterator.iterateTillFixpoint (ControlFlowSensitiveDFGPass.java:274)
|        at ControlFlowSensitiveDFGPass$FunctionLevelFixpointIterator.iterateTillFixpoint (ControlFlowSensitiveDFGPass.java:274)
|        at ControlFlowSensitiveDFGPass$FunctionLevelFixpointIterator.iterateTillFixpoint (ControlFlowSensitiveDFGPass.java:274)
|        at ControlFlowSensitiveDFGPass$FunctionLevelFixpointIterator.iterateTillFixpoint (ControlFlowSensitiveDFGPass.java:274)
|        at ControlFlowSensitiveDFGPass$FunctionLevelFixpointIterator.iterateTillFixpoint (ControlFlowSensitiveDFGPass.java:274)
```

**Comment by peckto** [comment]
When parsing `elua/src/lua/lcode.c` from `https://github.com/elua/elua` I get a similar error:
```
07:55:06,712 INFO  EvaluationOrderGraphPass Parsing of type class de.fraunhofer.aisec.cpg.graph.declarations.IncludeDeclaration is not supported (yet)
07:55:06,912 INFO  Benchmark EvaluationOrderGraphPass Executing Pass done in 279 ms
07:55:07,061 INFO  Benchmark TypeResolver Executing Pass done in 148 ms
07:55:07,418 INFO  Benchmark TranslationManager Translation into full graph done in 6149 ms
java.util.concurrent.ExecutionException: java.lang.StackOverflowError
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
        at de.fraunhofer.aisec.cpg_vis_neo4j.Application.call(Application.kt:241)
        at de.fraunhofer.aisec.cpg_vis_neo4j.Application.call(Application.kt:45)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
        at picocli.CommandLine.execute(CommandLine.java:1904)
        at de.fraunhofer.aisec.cpg_vis_neo4j.ApplicationKt.main(Application.kt:266)
Caused by: java.lang.StackOverflowError
        at java.base/java.util.stream.AbstractPipeline.wrapSink(AbstractPipeline.java:522)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at de.fraunhofer.aisec.cpg.graph.edge.PropertyEdge.unwrap(PropertyEdge.java:168)
        at de.fraunhofer.aisec.cpg.graph.edge.PropertyEdge.unwrap(PropertyEdge.java:153)
        at de.fraunhofer.aisec.cpg.graph.statements.Statement.getLocals(Statement.java:55)
        at de.fraunhofer.aisec.cpg.graph.statements.Statement.equals(Statement.java:80)
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.equals(Expression.java:232)
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.DeclaredReferenceExpression.equals(DeclaredReferenceExpression.java:206)
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.MemberExpression.equals(MemberExpression.java:73)
        at java.base/java.util.HashMap.getNode(HashMap.java:567)
        at java.base/java.util.HashMap.containsKey(HashMap.java:591)
        at java.base/java.util.HashSet.contains(HashSet.java:204)
        at java.base/java.util.AbstractSet.removeAll(AbstractSet.java:175)
        at de.fraunhofer.aisec.cpg.passes.ControlFlowSensitiveDFGPass$FunctionLevelFixpointIterator.eogTraversal(ControlFlowSensitiveDFGPass.java:130)
        at de.fraunhofer.aisec.cpg.passes.ControlFlowSensitiveDFGPass$FunctionLevelFixpointIterator.obtainAssignmentNode(ControlFlowSensitiveDFGPass.java:180)
        at de.fraunhofer.aisec.cpg.passes.ControlFlowSensitiveDFGPass$FunctionLevelFixpointIterator.handleDeclaredReferenceExpression(ControlFlowSensitiveDFGPass.java:301)
        at de.fraunhofer.aisec.cpg.passes.ControlFlowSensitiveDFGPass$FunctionLevelFixpointIterator.iterateTillFixpoint(ControlFlowSensitiveDFGPass.java:257)
        at de.fraunhofer.aisec.cpg.passes.ControlFlowSensitiveDFGPass$FunctionLevelFixpointIterator.iterateTillFixpoint(ControlFlowSensitiveDFGPass.java:272)
        at de.fraunhofer.aisec.cpg.passes.ControlFlowSensitiveDFGPass$FunctionLevelFixpointIterator.iterateTillFixpoint(ControlFlowSensitiveDFGPass.java:272)
[...]
```

Do you think, this bug is related to this Issue here?
At least, this bug seems to be resolved with #385.
```
