### ISSUE TITLE
NPE in `PropertyEdgeConverter`

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#453]
Seems to be introduced because of the template support (#368). I caught this when executing tests on the Codyze 4.0-support branch (https://github.com/Fraunhofer-AISEC/codyze/pull/184) in the test case `WpdsTest::testJavaMethodArgs` but it seems to creep up pretty much everywhere.

Definitely needs to be fixed before a 4.0 release.

```log
10:11:12,358 ERROR OverflowDatabase Error creating new de.fraunhofer.aisec.cpg.graph.statements.expressions.Literal node
java.lang.NullPointerException: null
	at de.fraunhofer.aisec.cpg.graph.edge.PropertyEdgeConverterManager.lambda$new$0(PropertyEdgeConverterManager.java:52) ~[cpg-v4.0.0-beta.1.jar:?]
	at de.fraunhofer.aisec.cpg.graph.edge.PropertyEdgeConverter.toEntityAttribute(PropertyEdgeConverter.java:83) ~[cpg-v4.0.0-beta.1.jar:?]
	at de.fraunhofer.aisec.crymlin.connectors.db.OverflowDatabase.rebuildPropertyEdges(OverflowDatabase.java:244) ~[main/:?]
	at de.fraunhofer.aisec.crymlin.connectors.db.OverflowDatabase.vertexToNode(OverflowDatabase.java:312) ~[main/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at de.fraunhofer.aisec.crymlin.connectors.db.OverflowDatabase.vertexToNode(OverflowDatabase.java:300) ~[main/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at de.fraunhofer.aisec.crymlin.connectors.db.OverflowDatabase.vertexToNode(OverflowDatabase.java:300) ~[main/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at de.fraunhofer.aisec.crymlin.connectors.db.OverflowDatabase.vertexToNode(OverflowDatabase.java:300) ~[main/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at de.fraunhofer.aisec.crymlin.connectors.db.OverflowDatabase.vertexToNode(OverflowDatabase.java:300) ~[main/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at de.fraunhofer.aisec.crymlin.connectors.db.OverflowDatabase.vertexToNode(OverflowDatabase.java:300) ~[main/:?]
	at de.fraunhofer.aisec.crymlin.connectors.db.OverflowDatabase.vertexToNode(OverflowDatabase.java:52) ~[main/:?]
	at de.fraunhofer.aisec.analysis.wpds.TypeStateAnalysis.createWpds(TypeStateAnalysis.java:407) ~[main/:?]
	at de.fraunhofer.aisec.analysis.wpds.TypeStateAnalysis.createWpds(TypeStateAnalysis.java:376) ~[main/:?]
	at de.fraunhofer.aisec.analysis.wpds.TypeStateAnalysis.analyze(TypeStateAnalysis.java:145) ~[main/:?]
	at de.fraunhofer.aisec.analysis.markevaluation.OrderEvaluator.evaluate(OrderEvaluator.java:43) ~[main/:?]
	at de.fraunhofer.aisec.analysis.markevaluation.ExpressionEvaluator.evaluateOrderExpression(ExpressionEvaluator.java:138) ~[main/:?]
	at de.fraunhofer.aisec.analysis.markevaluation.ExpressionEvaluator.evaluateExpression(ExpressionEvaluator.java:99) ~[main/:?]
	at de.fraunhofer.aisec.analysis.markevaluation.Evaluator.evaluateRules(Evaluator.java:192) ~[main/:?]
	at de.fraunhofer.aisec.analysis.markevaluation.Evaluator.evaluate(Evaluator.java:90) ~[main/:?]
	at de.fraunhofer.aisec.analysis.server.AnalysisServer.lambda$analyze$1(AnalysisServer.java:228) ~[main/:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) [?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
```

**Comment by oxisto** [comment]
Closed by #454
