### ISSUE TITLE
Errors in Go branch

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#478]
Seems to not cause too much problems, but annoying errors after the cleanup in #466

```
Exception in thread "ForkJoinPool.commonPool-worker-3" java.lang.NoSuchMethodError: connectToLocal
    at de.fraunhofer.aisec.cpg.frontends.golang.GoLanguageFrontend.parseInternal(Native Method)
    at de.fraunhofer.aisec.cpg.frontends.golang.GoLanguageFrontend.parse(GoLanguageFrontend.kt:51)
    at de.fraunhofer.aisec.cpg.TranslationManager.runFrontends(TranslationManager.java:239)
    at de.fraunhofer.aisec.cpg.TranslationManager.lambda$analyze$0(TranslationManager.java:98)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

```
Exception in thread "ForkJoinPool.commonPool-worker-3" java.lang.NoSuchFieldError: base
    at de.fraunhofer.aisec.cpg.frontends.golang.GoLanguageFrontend.parseInternal(Native Method)
    at de.fraunhofer.aisec.cpg.frontends.golang.GoLanguageFrontend.parse(GoLanguageFrontend.kt:51)
    at de.fraunhofer.aisec.cpg.TranslationManager.runFrontends(TranslationManager.java:239)
    at de.fraunhofer.aisec.cpg.TranslationManager.lambda$analyze$0(TranslationManager.java:98)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by oxisto** [comment]
It seems this was caused by an out of date `libcpgo.dylib`. Closing this.
