### ISSUE TITLE
EOG of IfStatement is incorrect

### ISSUE THREAD

**Issue by JulianSchuette** [Fraunhofer-AISEC/cpg#64]
Consider the following simple snippet:

```
if (inlen <= 0)
{
   EVP_EncryptUpdate(myctx, outbuf, &outlen, inbuf, inlen);
}
EVP_EncryptFinal_ex(ctx, outbuf, &outlen);
```
It results in the following EOG:
![eog-if-error](https://user-images.githubusercontent.com/1555755/75623871-f7ea8380-5bae-11ea-9e6e-018b3158cac6.png)

There is a single EOG edge from the `IfStatement` to `ctx` (the argument of the function call after the `then` block), but there are no EOG edges leading _into_ the `then` block). That is, code within `then` and `else` blocks never reachable by EOG edges.

This is incorrect and should be fixed as follows:
- in parallel to `CONDITION`, there should be an EOG edge from `IfStatement` to the condition (the opposite EOG edge from condition to `IfStatement` is correct and can remain)
- from the `IfStatement` there should be EOG edges
  - to the first expression in the `then` block (this one is missing)
  - to the first expression in the `else` block or if no explicit `else` exists, to the first expression after the `IfStatement`.

It should be guaranteed that an `IfStatement` has at least two outgoing EOG edges, plus the one to the condition and all nodes must be reachable via EOG

**Comment by konradweiss** [comment]
We will for now implement a second EOG that connects branching conditions and directly to the AST-root node of the language feature (e.g. if, for, switch) this is because the root node will specify the semantic of what is done with the result of the "expression" evaluation (e.g. condition for if and for, selector for the switch expression).

**Comment by JulianSchuette** [comment]
The new EOG looks good, but one of the tests still fails with StackOverflowError.

https://github.com/Fraunhofer-AISEC/cpg/runs/490174829#step:4:97

Failing test case: `DemoTests.testHierarchy()`

Stack trace:

```
java.lang.StackOverflowError
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.pushToEOG(EvaluationOrderGraphPass.java:786)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.createEOG(EvaluationOrderGraphPass.java:594)
	at de.fraunhofer.aisec.cpg.passes.BranchSemanticEOGPass.handleConditionalExpression(BranchSemanticEOGPass.java:39)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.createEOG(EvaluationOrderGraphPass.java:574)
	at de.fraunhofer.aisec.cpg.passes.BranchSemanticEOGPass.handleConditionalExpression(BranchSemanticEOGPass.java:40)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.createEOG(EvaluationOrderGraphPass.java:574)
	at de.fraunhofer.aisec.cpg.passes.BranchSemanticEOGPass.handleConditionalExpression(BranchSemanticEOGPass.java:40)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.createEOG(EvaluationOrderGraphPass.java:574)
```
