### ISSUE TITLE
java.lang.ClassCastException when running a specific file from the abyss project

### ISSUE THREAD

**Issue by xaviergeorge** [Fraunhofer-AISEC/cpg#648]
When cpg runs the file https://github.com/bcgsc/abyss/blob/master/DataBase/DB.h , it gives an error which is 

`java.util.concurrent.ExecutionException: java.lang.ClassCastException: class de.fraunhofer.aisec.cpg.passes.scopes.RecordScope cannot be cast to class de.fraunhofer.aisec.cpg.passes.scopes.FunctionScope (de.fraunhofer.aisec.cpg.passes.scopes.RecordScope and de.fraunhofer.aisec.cpg.passes.scopes.FunctionScope are in unnamed module of loader 'app')
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2063)
	at de.fraunhofer.aisec.cpg_vis_neo4j.Application.call(Application.kt:322)
	at de.fraunhofer.aisec.cpg_vis_neo4j.Application.call(Application.kt:70)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at de.fraunhofer.aisec.cpg_vis_neo4j.ApplicationKt.main(Application.kt:349)
Caused by: java.lang.ClassCastException: class de.fraunhofer.aisec.cpg.passes.scopes.RecordScope cannot be cast to class de.fraunhofer.aisec.cpg.passes.scopes.FunctionScope (de.fraunhofer.aisec.cpg.passes.scopes.RecordScope and de.fraunhofer.aisec.cpg.passes.scopes.FunctionScope are in unnamed module of loader 'app')
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.handleFunctionDeclaration(EvaluationOrderGraphPass.java:366)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.createEOG(EvaluationOrderGraphPass.java:415)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.handleRecordDeclaration(EvaluationOrderGraphPass.java:308)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.createEOG(EvaluationOrderGraphPass.java:415)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.handleTranslationUnitDeclaration(EvaluationOrderGraphPass.java:271)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.createEOG(EvaluationOrderGraphPass.java:415)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.accept(EvaluationOrderGraphPass.java:168)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.accept(EvaluationOrderGraphPass.java:73)
	at de.fraunhofer.aisec.cpg.TranslationManager.analyze$lambda-2(TranslationManager.kt:96)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)`

Parsing of the whole project also gives an error which is mentioned in an another issue. 
I'm at the commit [a20309fe3259bfec6205dcd692c508b78f9edf8d](https://github.com/Fraunhofer-AISEC/cpg/tree/a20309fe3259bfec6205dcd692c508b78f9edf8d).

**Comment by xaviergeorge** [comment]
Commenting the line https://github.com/bcgsc/abyss/blob/master/DataBase/DB.h#L90 from this file makes the program run without error.
The line is 
`srand(time(NULL));`

**Comment by oxisto** [comment]
Looking into this; for some reason, our parser thinks that `srand(time(NULL));` is actually a function declaration inside the method declaration, instead of a call. Which seems very weird. After that, everything goes wrong.

**Comment by oxisto** [comment]
The problem seems to go away if we properly define the symbol `NULL`, either as `0` or as C++ `nullptr`. I wonder, if this would be something we should as default?

**Comment by oxisto** [comment]
Marking this as blocked until we move to tree-sitter (see #604). I will try to mitigate this in a patch, so that it does not crash.
