### ISSUE TITLE
ConcurrentException 

### ISSUE THREAD

**Issue by anon767** [Fraunhofer-AISEC/cpg#651]
Hey,
I receive a concurrentException on some occurrences when enabling useParallelFrontends(true).
I can't tell what the root cause is. However, this is my TranslationConfiguration:
```
        val translationConfiguration = TranslationConfiguration.builder()
            .sourceLocations(filePaths)
            .defaultPasses()
            .defaultLanguages()
            .processAnnotations(true)
            .codeInNodes(true)
            .debugParser(false)
            .failOnError(false)
            .symbols(symbols)
            .useParallelFrontends(true)
            .typeSystemActiveInFrontend(true)
        return TranslationManager.builder().config(translationConfiguration.build()).build()
```

filePaths is a list of completely independent .c files from different projects. Might that be the problem?

Here is the stack trace:

```
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.IdentityHashMap$IdentityHashMapIterator.nextIndex(IdentityHashMap.java:737)
	at java.base/java.util.IdentityHashMap$EntryIterator.next(IdentityHashMap.java:845)
	at java.base/java.util.IdentityHashMap$EntryIterator.next(IdentityHashMap.java:839)
	at java.base/java.util.IdentityHashMap.putAll(IdentityHashMap.java:508)
	at de.fraunhofer.aisec.cpg.passes.scopes.ScopeManager.mergeFrom(ScopeManager.kt:183)
	at de.fraunhofer.aisec.cpg.TranslationManager.parseParallel(TranslationManager.kt:267)
	at de.fraunhofer.aisec.cpg.TranslationManager.runFrontends(TranslationManager.kt:203)
	at de.fraunhofer.aisec.cpg.TranslationManager.analyze$lambda-2(TranslationManager.kt:86)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

Thanks in advance

**Comment by oxisto** [comment]
You need to set `typeSystemActiveInFrontend` to false, there should be a warning about this in the log. I know, the log is kind of full of warnings ;) The types will be set / activated after all frontends have been run successfully. In the future we want to remove this little hack and make the type parsing in parallel frontends more parallel
