### ISSUE TITLE
Stackoverflow Exception

### ISSUE THREAD

**Issue by anon767** [Fraunhofer-AISEC/cpg#679]
Hi,
I encountered a Stackoverflow exception in the scope manager. Can't really reproduce it since it appears to occur more or less random to me.
```
Caused by: java.lang.StackOverflowError
        at java.util.Objects.equals(Objects.java:77) ~[?:?]
        at de.fraunhofer.aisec.cpg.graph.types.ObjectType.equals(ObjectType.java:181) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.passes.scopes.ScopeManager.getCurrentTypedefs$lambda-15(ScopeManager.kt:584) ~[cpg-core-master-SNAPSHOT.jar:?]
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1631) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.noneMatch(ReferencePipeline.java:538) ~[?:?]
        at de.fraunhofer.aisec.cpg.passes.scopes.ScopeManager.getCurrentTypedefs(ScopeManager.kt:582) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.passes.scopes.ScopeManager.getCurrentTypedefs(ScopeManager.kt:581) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.passes.scopes.ScopeManager.getCurrentTypedefs(ScopeManager.kt:581) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.passes.scopes.ScopeManager.getCurrentTypedefs(ScopeManager.kt:581) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.passes.scopes.ScopeManager.getCurrentTypedefs(ScopeManager.kt:581) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.passes.scopes.ScopeManager.getCurrentTypedefs(ScopeManager.kt:100) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.TypeManager.resolvePossibleTypedef(TypeManager.java:741) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.types.TypeParser.createFromUnsafe(TypeParser.java:846) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.types.TypeParser.createFrom(TypeParser.java:887) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.TypeManager.lambda$getCommonType$10(TypeManager.java:492) ~[cpg-core-master-SNAPSHOT.jar:?]
        at java.util.Optional.map(Optional.java:265) ~[?:?]
        at de.fraunhofer.aisec.cpg.graph.TypeManager.getCommonType(TypeManager.java:492) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.TypeManager.isSupertypeOf(TypeManager.java:570) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.lambda$setType$1(Expression.java:147) ~[cpg-core-master-SNAPSHOT.jar:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.setType(Expression.java:148) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.BinaryOperator.typeChanged(BinaryOperator.java:200) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.lambda$setType$4(Expression.java:160) ~[cpg-core-master-SNAPSHOT.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.setType(Expression.java:160) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.DeclaredReferenceExpression.typeChanged(DeclaredReferenceExpression.java:145) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.lambda$setType$4(Expression.java:160) ~[cpg-core-master-SNAPSHOT.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.setType(Expression.java:160) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.BinaryOperator.typeChanged(BinaryOperator.java:200) ~[cpg-core-master-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.lambda$setType$4(Expression.java:160) ~[cpg-core-master-SNAPSHOT.jar:?]
```
I guess thats a problem in the TypeManager or ScopeManager right?
I triggered that exception when parsing in the entire FFmpeg project and using UseParallelFrontend
Regards,
Tom

**Comment by anon767** [comment]
This happens when trying to parse [FFmpeg](https://github.com/FFmpeg/FFmpeg/tree/9bd8bd1add6be33f5eb7f2645350901ab2a56a6c) 

I tried to pin down the file that causes the exception but the logs aren't that helpful:

```
20:53:03,254 INFO  Benchmark TranslationManager: Translation into full graph done in 53793 ms
20:53:03,254 DEBUG TranslationManager Cleaning up 0 Passes
20:53:03,254 DEBUG TranslationManager Cleaning up null Frontends
20:53:03,254 INFO  Application Could not parse file [/tmp/FFmpeg/libavcodec/mpegaudio.h, /tmp/FFmpeg/libavcodec/armv4l/dsputil_arm.c, /tmp/FFmpeg/libavcodec/mpegaudiotab.h, /tmp/FFmpeg/libavcodec/mlib/dsputil_mlib.c, /tmp/FFmpeg/lib
avcodec/dsputil.h, /tmp/FFmpeg/libavcodec/fdctref.c, /tmp/FFmpeg/libavcodec/ac3dec.c, /tmp/FFmpeg/libavcodec/h263dec.c, /tmp/FFmpeg/libavcodec/alpha/asm.h, /tmp/FFmpeg/libavcodec/alpha/pixops.h, /tmp/FFmpeg/libavcodec/alpha/dsputil_alpha.c, /tmp/FFmpeg/l
ibavcodec/alpha/mpegvideo_alpha.c, /tmp/FFmpeg/libavcodec/common.c, /tmp/FFmpeg/libavcodec/jfdctfst.c, /tmp/FFmpeg/libavcodec/mpeg12.c, /tmp/FFmpeg/libavcodec/i386/dsputil_mmx_avg.h, /tmp/FFmpeg/libavcodec/i386/mpegvideo_mmx.c, /tmp/FFmpeg/libavcodec/i38
6/mmx.h, /tmp/FFmpeg/libavcodec/i386/simple_idct_mmx.c, /tmp/FFmpeg/libavcodec/i386/mpegvideo_mmx_template.c, /tmp/FFmpeg/libavcodec/i386/idct_mmx.c, /tmp/FFmpeg/libavcodec/i386/fdct_mmx.c, /tmp/FFmpeg/libavcodec/i386/motion_est_mmx.c, /tmp/FFmpeg/libavc
odec/i386/dsputil_mmx.c, /tmp/FFmpeg/libavcodec/mpegaudiodec.c, /tmp/FFmpeg/libavcodec/ac3enc.h, /tmp/FFmpeg/libavcodec/imgresample.c, /tmp/FFmpeg/libavcodec/imgconvert.c, /tmp/FFmpeg/libavcodec/rv10.c, /tmp/FFmpeg/libavcodec/jrevdct.c, /tmp/FFmpeg/libav
codec/mpeg12data.h, /tmp/FFmpeg/libavcodec/libac3/imdct.c, /tmp/FFmpeg/libavcodec/libac3/bit_allocate.c, /tmp/FFmpeg/libavcodec/libac3/ac3_internal.h, /tmp/FFmpeg/libavcodec/libac3/downmix.c, /tmp/FFmpeg/libavcodec/libac3/tables.h, /tmp/FFmpeg/libavcodec
/libac3/parse.c, /tmp/FFmpeg/libavcodec/libac3/bitstream.c, /tmp/FFmpeg/libavcodec/libac3/bitstream.h, /tmp/FFmpeg/libavcodec/libac3/ac3.h, /tmp/FFmpeg/libavcodec/mpeg4data.h, /tmp/FFmpeg/libavcodec/mpegvideo.h, /tmp/FFmpeg/libavcodec/msmpeg4.c, /tmp/FFm
peg/libavcodec/simple_idct.h, /tmp/FFmpeg/libavcodec/ac3enc.c, /tmp/FFmpeg/libavcodec/h263data.h, /tmp/FFmpeg/libavcodec/mpegaudiodectab.h, /tmp/FFmpeg/libavcodec/avcodec.h, /tmp/FFmpeg/libavcodec/utils.c, /tmp/FFmpeg/libavcodec/dsputil.c, /tmp/FFmpeg/li
bavcodec/common.h, /tmp/FFmpeg/libavcodec/mjpeg.c, /tmp/FFmpeg/libavcodec/simple_idct.c, /tmp/FFmpeg/libavcodec/motion_est.c, /tmp/FFmpeg/libavcodec/pcm.c, /tmp/FFmpeg/libavcodec/mpegaudio.c, /tmp/FFmpeg/libavcodec/h263.c, /tmp/FFmpeg/libavcodec/mpegvide
o.c, /tmp/FFmpeg/libavcodec/resample.c, /tmp/FFmpeg/libavcodec/ac3tab.h, /tmp/FFmpeg/libavcodec/msmpeg4data.h, /tmp/FFmpeg/libavcodec/mangle.h, /tmp/FFmpeg/libavcodec/fastmemcpy.h, /tmp/FFmpeg/libav/avio.c, /tmp/FFmpeg/libav/avi.h, /tmp/FFmpeg/libav/file
.c, /tmp/FFmpeg/libav/http.c, /tmp/FFmpeg/libav/img.c, /tmp/FFmpeg/libav/udp.c, /tmp/FFmpeg/libav/audio.c, /tmp/FFmpeg/libav/avio.h, /tmp/FFmpeg/libav/raw.c, /tmp/FFmpeg/libav/asf.c, /tmp/FFmpeg/libav/mpeg.c, /tmp/FFmpeg/libav/grab.c, /tmp/FFmpeg/libav/a
videc.c, /tmp/FFmpeg/libav/wav.c, /tmp/FFmpeg/libav/utils.c, /tmp/FFmpeg/libav/rm.c, /tmp/FFmpeg/libav/ffm.c, /tmp/FFmpeg/libav/jpeg.c, /tmp/FFmpeg/libav/avienc.c, /tmp/FFmpeg/libav/aviobuf.c, /tmp/FFmpeg/libav/avformat.h, /tmp/FFmpeg/libav/swf.c, /tmp/F
Fmpeg/postproc/swscale_template.c, /tmp/FFmpeg/postproc/yuv2rgb_template.c, /tmp/FFmpeg/postproc/rgb2rgb_template.c, /tmp/FFmpeg/postproc/swscale.c, /tmp/FFmpeg/postproc/yuv2rgb_mlib.c, /tmp/FFmpeg/postproc/swscale.h, /tmp/FFmpeg/postproc/rgb2rgb.h, /tmp
/FFmpeg/postproc/postprocess.h, /tmp/FFmpeg/postproc/postprocess_template.c, /tmp/FFmpeg/postproc/postprocess.c, /tmp/FFmpeg/postproc/rgb2rgb.c, /tmp/FFmpeg/postproc/yuv2rgb.c, /tmp/FFmpeg/ffserver.c, /tmp/FFmpeg/bswap.h, /tmp/FFmpeg/ffmpeg.c, /tmp/FFmpe
g/mangle.h]
java.util.concurrent.ExecutionException: java.lang.StackOverflowError
```
