### ISSUE TITLE
Stackoverflow Exception in `setPossibleSubTypes`

### ISSUE THREAD

**Issue by anon767** [Fraunhofer-AISEC/cpg#685]
Hey,

here is another SOE that occur when parsing large projects. 

```
Caused by: java.lang.StackOverflowError
        at java.util.HashMap.hash(HashMap.java:339) ~[?:?]
        at java.util.HashMap.put(HashMap.java:607) ~[?:?]
        at java.util.HashSet.add(HashSet.java:220) ~[?:?]
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.setPossibleSubTypes(Expression.java:177) ~[cpg-core-fix-stack-overflow-typedefs-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.ArraySubscriptionExpression.possibleSubTypesChanged(ArraySubscriptionExpression.java:98) ~[cpg-core-fix-stack-overflow-typedefs-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.lambda$setPossibleSubTypes$7(Expression.java:198) ~[cpg-core-fix-stack-overflow-typedefs-SNAPSHOT.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.setPossibleSubTypes(Expression.java:198) ~[cpg-core-fix-stack-overflow-typedefs-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.BinaryOperator.possibleSubTypesChanged(BinaryOperator.java:220) ~[cpg-core-fix-stack-overflow-typedefs-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.lambda$setPossibleSubTypes$7(Expression.java:198) ~[cpg-core-fix-stack-overflow-typedefs-SNAPSHOT.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.setPossibleSubTypes(Expression.java:198) ~[cpg-core-fix-stack-overflow-typedefs-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.HasType.setPossibleSubTypes(HasType.java:68) ~[cpg-core-fix-stack-overflow-typedefs-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.setType(Expression.java:155) ~[cpg-core-fix-stack-overflow-typedefs-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.DeclaredReferenceExpression.typeChanged(DeclaredReferenceExpression.java:145) ~[cpg-core-fix-stack-overflow-typedefs-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.lambda$setType$4(Expression.java:160) ~[cpg-core-fix-stack-overflow-typedefs-SNAPSHOT.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.setType(Expression.java:160) ~[cpg-core-fix-stack-overflow-typedefs-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.BinaryOperator.typeChanged(BinaryOperator.java:200) ~[cpg-core-fix-stack-overflow-typedefs-SNAPSHOT.jar:?]
        at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.lambda$setType$4(Expression.java:160) ~[cpg-core-fix-stack-overflow-typedefs-SNAPSHOT.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
```

Regards,
Tom

**Comment by anon767** [comment]
Any progress on that one so far?
Would it be possible to just add a maximum stack call depth that should be respected when _failOnError_ is set to _false_ ?

**Comment by oxisto** [comment]
> Any progress on that one so far?
> Would it be possible to just add a maximum stack call depth that should be respected when _failOnError_ is set to _false_ ?

Unfortunately not, as we also only have limited resources working on this project :)

**Comment by anon767** [comment]
I wish I could be more helpful. And my QA skills are a bit lacking too :D

**Comment by KuechA** [comment]
Hi @anon767 it's been a while now that you opened this issue but I recently came across a similar (the same?) problem. Could you check #752 and see if it fixes the problem or at least if there's some kind of improvement? :)

**Comment by oxisto** [comment]
Closing this due to inactivity, we close a lot of these loops in recent releases.
