### ISSUE TITLE
java.lang.IllegalStateException in VariableUsageResolver

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/cpg#821]
# Stack trace

```
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Duplicate key FunctionPointerType{parameters=[de.fraunhofer.aisec.cpg.graph.edge.PropertyEdge@1b4e93a6], returnType=ObjectType[name=QtPrivate.FunctionPointer<Ret], typeName='', storage=AUTO, qualifier=Qualifier{isConst=false, isVolatile=false, isRestrict=false, isAtomic=false}, origin=UNRESOLVED} (attempted merging values [] and [])
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
        at de.fraunhofer.aisec.cpg_vis_neo4j.Application.call(Application.kt:408)
        at de.fraunhofer.aisec.cpg_vis_neo4j.Application.call(Application.kt:70)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at de.fraunhofer.aisec.cpg_vis_neo4j.ApplicationKt.main(Application.kt:448)
Caused by: java.lang.IllegalStateException: Duplicate key FunctionPointerType{parameters=[de.fraunhofer.aisec.cpg.graph.edge.PropertyEdge@1b4e93a6], returnType=ObjectType[name=QtPrivate.FunctionPointer<Ret], typeName='', storage=AUTO, qualifier=Qualifier{isConst=false, isVolatile=false, isRestrict=false, isAtomic=false}, origin=UNRESOLVED} (attempted merging values [] and [])
        at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:133)
        at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
        at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1693)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at de.fraunhofer.aisec.cpg.passes.VariableUsageResolver.accept(VariableUsageResolver.java:100)
        at de.fraunhofer.aisec.cpg.passes.VariableUsageResolver.accept(VariableUsageResolver.java:68)
        at de.fraunhofer.aisec.cpg.TranslationManager.analyze$lambda-2(TranslationManager.kt:102)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by oxisto** [comment]
The problem is this construct here:
```
    Map<Type, List<Type>> currSuperTypes =
        recordMap.values().stream()
            .collect(
                Collectors.toMap(
                    r -> TypeParser.createFrom(r.getName(), true),
                    RecordDeclaration::getSuperTypes));
    superTypesMap.putAll(currSuperTypes);
```

It seems, that even though the types in the record map are already unique, the newly created typed in the toMap function is not.
