### ISSUE TITLE
NullPointerException in updateTemplateParameters due to error in CallResolver

### ISSUE THREAD

**Issue by peckto** [Fraunhofer-AISEC/cpg#878]
In case only the implementation of a method is available (not the declaration), the CallResolver does not distinguish between methods of the same name but in different classes.

# Stack trace

```
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Parameter specified as non-null is null: method de.fraunhofer.aisec.cpg.graph.edge.PropertyEdge.<init>, parameter end
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at de.fraunhofer.aisec.cpg_vis_neo4j.Application.call(Application.kt:410)
	at de.fraunhofer.aisec.cpg_vis_neo4j.Application.call(Application.kt:70)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at de.fraunhofer.aisec.cpg_vis_neo4j.ApplicationKt.main(Application.kt:450)
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method de.fraunhofer.aisec.cpg.graph.edge.PropertyEdge.<init>, parameter end
	at de.fraunhofer.aisec.cpg.graph.edge.PropertyEdge.<init>(PropertyEdge.kt)
	at de.fraunhofer.aisec.cpg.graph.statements.expressions.CallExpression.updateTemplateParameters(CallExpression.kt:223)
	at de.fraunhofer.aisec.cpg.passes.CallResolver.applyTemplateInstantiation(CallResolver.java:668)
	at de.fraunhofer.aisec.cpg.passes.CallResolver.handleTemplateFunctionCalls(CallResolver.java:584)
	at de.fraunhofer.aisec.cpg.passes.CallResolver.handleCXXMethodCall(CallResolver.java:1194)
	at de.fraunhofer.aisec.cpg.passes.CallResolver.handleMethodCall(CallResolver.java:1135)
	at de.fraunhofer.aisec.cpg.passes.CallResolver.handleCallExpression(CallResolver.java:299)
	at de.fraunhofer.aisec.cpg.passes.CallResolver.resolve(CallResolver.java:281)
	at de.fraunhofer.aisec.cpg.helpers.SubgraphWalker$ScopedWalker.lambda$registerHandler$0(SubgraphWalker.java:413)
	at de.fraunhofer.aisec.cpg.helpers.SubgraphWalker$ScopedWalker.handleNode(SubgraphWalker.java:450)
	at de.fraunhofer.aisec.cpg.helpers.SubgraphWalker$ScopedWalker.lambda$iterate$1(SubgraphWalker.java:423)
	at de.fraunhofer.aisec.cpg.helpers.SubgraphWalker$IterativeGraphWalker.lambda$iterate$1(SubgraphWalker.java:338)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at de.fraunhofer.aisec.cpg.helpers.SubgraphWalker$IterativeGraphWalker.iterate(SubgraphWalker.java:338)
	at de.fraunhofer.aisec.cpg.helpers.SubgraphWalker$ScopedWalker.iterate(SubgraphWalker.java:425)
	at de.fraunhofer.aisec.cpg.passes.CallResolver.accept(CallResolver.java:104)
	at de.fraunhofer.aisec.cpg.passes.CallResolver.accept(CallResolver.java:65)
	at de.fraunhofer.aisec.cpg.TranslationManager.analyze$lambda-2(TranslationManager.kt:101)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

# Code of interest

## a)

```cpp
void B::foo() {
}

int main() {
    A a;
    a.foo();

    return 0;
}

```

![image](https://user-images.githubusercontent.com/2060591/185308970-eef7b76a-290f-440b-b89e-1e6653391542.png)

## b)

```cpp
template <class T>
void B<T>::foo() {
}

int main() {
    A a;
    a.foo();

    return 0;
}

```

# Extensions to the library, e.g. added or changed LanguageFrontends or Passes

None

# Changes to the configuration

None

**Comment by peckto** [comment]
fixed by #1028
