### ISSUE TITLE
Signer information does not match signer information of other classes in the same package

### ISSUE THREAD

**Issue by anon767** [Fraunhofer-AISEC/cpg#916]
Hi everyone

# Stack trace
```
Caused by: java.lang.ExceptionInInitializerError
	at org.eclipse.cdt.core.dom.parser.AbstractCLikeLanguage.createScanner(AbstractCLikeLanguage.java:279)
	at org.eclipse.cdt.core.dom.parser.AbstractCLikeLanguage.getASTTranslationUnit(AbstractCLikeLanguage.java:145)
	at de.fraunhofer.aisec.cpg.frontends.cpp.CXXLanguageFrontend.parse(CXXLanguageFrontend.kt:199)
	at de.fraunhofer.aisec.cpg.TranslationManager.parse(TranslationManager.kt:345)
	at de.fraunhofer.aisec.cpg.TranslationManager.parseSequentially(TranslationManager.kt:289)
	at de.fraunhofer.aisec.cpg.TranslationManager.runFrontends(TranslationManager.kt:209)
	at de.fraunhofer.aisec.cpg.TranslationManager.analyze$lambda-2(TranslationManager.kt:91)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.SecurityException: class "org.eclipse.core.runtime.Plugin"'s signer information does not match signer information of other classes in the same package
	at java.base/java.lang.ClassLoader.checkCerts(ClassLoader.java:1158)
	at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:902)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.eclipse.cdt.internal.core.parser.scanner.CPreprocessor.getCDTVersion(CPreprocessor.java:139)
	at org.eclipse.cdt.internal.core.parser.scanner.CPreprocessor.<clinit>(CPreprocessor.java:105)
	... 14 more
```

# Unexpected behavior

This error recently started occuring. Reminds me on https://github.com/Fraunhofer-AISEC/cpg/issues/472 

# Gradle

```
repositories {
    ivy {
        setUrl("https://download.eclipse.org/tools/cdt/releases/10.3/cdt-10.3.2/plugins")
        metadataSources {
            artifact()
        }
        patternLayout {
            artifact("/[organisation].[module]_[revision].[ext]")
        }
    }
}

dependencies {
    var cpgVersion = "4.3.0" 
    
    api("de.fraunhofer.aisec", "cpg-core", cpgVersion)
   
}
```

Kind regards,
Tom

**Comment by oxisto** [comment]
UNfortunatly, this is a problem that occurs every time eclipse updates its core platform dependency. They somehow "destroy" the old file in doing so. On `main` we already updated to the latest one (https://github.com/Fraunhofer-AISEC/cpg/pull/906).

However, we have some breaking changes on `main` that will be released as `v5`. I have back ported this to the `v4` as `v4.6.3` which should be available on Maven central in a couple of hours.

**Comment by oxisto** [comment]
https://github.com/Fraunhofer-AISEC/cpg/releases/tag/v4.6.3 is released. Should sync to maven central in a while.
