### ISSUE TITLE
ValueEvaluator causes StackOverflow when evaluating Expressions containing += 

### ISSUE THREAD

**Issue by MaximilianLincks** [Fraunhofer-AISEC/cpg#948]
I am trying to analyse the value of "s" in the println statement. The error occurs due to DFG Edges leading from s to the += operator and from the += operator back to s.

When the assignement is done using the following code, everything works alright,
```
s = s + "!"
```

# Stack trace

Exception in thread "main" java.lang.StackOverflowError
	at java.base/java.util.HashSet.iterator(HashSet.java:174)
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:199)
	at de.fraunhofer.aisec.cpg.analysis.ValueEvaluator.handleDeclaredReferenceExpression(ValueEvaluator.kt:357)
	at de.fraunhofer.aisec.cpg.analysis.ValueEvaluator.evaluateInternal(ValueEvaluator.kt:87)
	at de.fraunhofer.aisec.cpg.analysis.ValueEvaluator.handleBinaryOperator(ValueEvaluator.kt:109)
	at de.fraunhofer.aisec.cpg.analysis.ValueEvaluator.evaluateInternal(ValueEvaluator.kt:89)
	at de.fraunhofer.aisec.cpg.analysis.ValueEvaluator.handleDeclaredReferenceExpression(ValueEvaluator.kt:357)
	at de.fraunhofer.aisec.cpg.analysis.ValueEvaluator.evaluateInternal(ValueEvaluator.kt:87)
	at de.fraunhofer.aisec.cpg.analysis.ValueEvaluator.handleBinaryOperator(ValueEvaluator.kt:109)
	at de.fraunhofer.aisec.cpg.analysis.ValueEvaluator.evaluateInternal(ValueEvaluator.kt:89)
	at de.fraunhofer.aisec.cpg.analysis.ValueEvaluator.handleDeclaredReferenceExpression(ValueEvaluator.kt:357)
	at de.fraunhofer.aisec.cpg.analysis.ValueEvaluator.evaluateInternal(ValueEvaluator.kt:87)
	at de.fraunhofer.aisec.cpg.analysis.ValueEvaluator.handleBinaryOperator(ValueEvaluator.kt:109)
	at de.fraunhofer.aisec.cpg.analysis.ValueEvaluator.evaluateInternal(ValueEvaluator.kt:89)
	at de.fraunhofer.aisec.cpg.analysis.ValueEvaluator.handleDeclaredReferenceExpression(ValueEvaluator.kt:357)
	at de.fraunhofer.aisec.cpg.analysis.ValueEvaluator.evaluateInternal(ValueEvaluator.kt:87)
	at de.fraunhofer.aisec.cpg.analysis.ValueEvaluator.handleBinaryOperator(ValueEvaluator.kt:109)
...

# Code of interest

```
 int i = 3;
        String s;
        if(i < 2)
            s = "small";
        else
            s = "big";
        s += "!";
        System.out.println(s);
```

**Comment by oxisto** [comment]
Ah, interesting. The DFG edges are probably there since there is a read and write dataflow to `s`. Looks like we need to handle this explicitly in the value evaluator.

**Comment by oxisto** [comment]
The good news: I know how to fix this :)
The bad news: I cannot fix it until https://github.com/Fraunhofer-AISEC/cpg/pull/925 is merged in.

**Comment by oxisto** [comment]
Both issues should be fixed now and we now also support `++`. I will trigger a new release with this and the improvements to the DFG soon.
